### ISSUE TITLE
Cannot allocate memory on large tables

### ISSUE THREAD

**Issue by jmbmxer** [sunitparekh/data-anonymization#32] opened 2016-02-19 16:22 UTC
I have been running into issues anonymizing certain tables even while using batch processing.  The table in question has 2,720,219 rows. I have tried using batch = 1000 and batch = 100 and am still running into memory issues. For reference, this DB server is running on an r3.2xlarge instance on AWS which is aprox. 61 gigs of ram. Any tips to manage memory on tables on this size beyond using batch sizes?

`E, [2016-02-19T01:22:50.023154 #22017] ERROR -- :
Cannot allocate memory - stty size 2>/dev/null`

**Comment by sunitparekh** [comment] 2016-02-20 01:54
If my guess is correct, the error is due to memory issue where data-anon tool is running. Honestly, I haven't tested it on such a large scale so please bare with me. However, I am looking forward to look into and fix issues with data-anon tool.

To debug issue, can you please share your ruby version, gem versions (list) and current config of server (CPU, RAM, etc) running data-anon tool.  

Let me do the test and reproduce the same error on local machine, so I can fix the issue. Give me sometime.

meanwhile tryout, 
1) you can tryout increasing the swap size on machine where you are running the data-anon tool as mentioned here. 
http://stackoverflow.com/questions/28286002/ruby-cannot-allocate-memory   
2) ruby memory configuration as mentioned in the article 
http://tmm1.net/ruby21-rgengc/

**Comment by tomdev** [comment] 2016-08-11 13:20
A little late to the party, but improving the ruby memory configuration helps a lot. By using the example settings from http://tmm1.net/ruby21-rgengc/ I was able to decrease memory usage from 4500MB to 600MB when running on large tables.

**Comment by sunitparekh** [comment] 2016-08-18 13:30
As mentioned using appropriate memory settings http://tmm1.net/ruby21-rgengc/ memory usage can be decreased. So closing the issue.

**Closed by sunitparekh** 2016-08-18 13:30 UTC
